package src

const (
	CLEARTERMINAL = "clearT"
	CHECKCREDS    = `** WARNING ** PLEASE PRESS CORRECT INPUTS `
	EXITAPP       = "PRESS ENTER TO RETURN TO THE MAIN MENU OR PRESS 9 TO EXIT"
	GOODBYENOTE   = " -------  CLOSING THE APPLICATION $$$$$$$ THANKS FOR VISITING --------"
)
